algoritmo "Pos_Neg"
// Função :  Verificar se o número digitado é positivo ou negativo
// Autor :   Elys_Sanntos
// Data : 01/03/2020
// Seção de Declarações
var
valor : inteiro
inicio

escreva("Digite um Numero: ")
Leia(valor)


SE (valor > 0) ENTAO
   Escreva ("O Numero digitado é POSITIVO")
SENAO
   SE (valor < 0) ENTAO
      escreva("O Nuero digitado é NEGATIVO")
   FIMSE
   
   SE (valor = 0) ENTAO
      Escreva ("O numero digitado é Zero")
   FIMSE





fimalgoritmo

FIMSE
fimalgoritmo
